version: 2
updates:
  # dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
  # dependencies for bundler
  - package-ecosystem: 'bundler'
    directory: '/'
    schedule:
      interval: 'weekly'
