AllCops:
  TargetRubyVersion: 2.3
  DisabledByDefault: true
  Exclude:
    - doc/**/*.rb
    - rake.gemspec
    - bin/*

Metrics/LineLength:
  Enabled: true
  Max: 120

Style/HashSyntax:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/MultilineIfThen:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Style/BracesAroundHashParameters:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true

Layout/Tab:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/TrailingBlankLines:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Layout/CaseIndentation:
  Enabled: true

Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: variable
