# Rakefile for rake        -*- ruby -*-

require 'build/rubyapp'
require 'rake/testtask'
require 'rake/packagetask'

task :default => :test

builder = AppBuilder.new('rake')
builder.revision_command "ruby -Ilib ./bin/rake --version"


pkg = Rake::PackageTask.new("rake", "0.2.7c")
pkg.package_files << 'install.rb'
pkg.package_files.add(
  '[A-Z]*',
  'bin/**/*', 
  'lib/**/*.rb', 
  'test/**/*.rb',
  'doc/**/*',
  'build/rubyapp.rb',
  '*.blurb')
pkg.package_files.reject! { |fn| fn =~ /\bCVS\b|~$/ }
pkg.define


builder.rdoc_files << ['README', 'LICENSE', 'TODO', 'CHANGES']
#builder.rdoc_files.glob('lib/**/*.rb', 'doc/**/*.rdoc', 'test/*.rb')

builder.clobber_files << %w(html pkg testdata)

builder.create_tasks

t = Rake::TestTask.new
t.libs << "test"
t.verbose = true
t.define

umlcoop_info = HostInfo.new(
  'umlcoop',
  'htdocs/software',
  'htdocs/packages')

local_info = HostInfo.new(
  'localhost',
  'working/projects/source2html/dummy/software',
  'working/projects/source2html/dummy/packages')

class RubyForgePublisher < SshDirPublisher
  attr_reader :project, :proj_id, :user

  def initialize(projname, user)
    super(
      "#{user}@rubyforge.org",
      "/var/www/gforge-projects/#{projname}",
      "html")
  end
end

builder.web_publisher.add RubyForgePublisher.new('rake', 'jimweirich')
builder.web_publisher.add SshFilePublisher.new(
  'umlcoop',
  'htdocs/software/rake',
  '.',
  'rake.blurb')

# Additional dependencies beyond the standard

directory 'testdata'
task :test => ['testdata']

ctest = Rake::TestTask.new(:contrib_test)
ctest.pattern = 'test/contrib/test*.rb'
ctest.verbose = true
ctest.define

task :testall => [:test, :contrib_test]
