# Rakefile for rake        -*- ruby -*-

require 'build/rubyapp'

builder = AppBuilder.new('rake')
builder.revision_command "ruby -Ilib ./bin/rake --version"

builder.package_files << 'install.rb'
builder.package_files.no_match(/\bCVS\b/, /~$/)
builder.package_files.glob(
  '[A-Z]*',
  'bin/**/*', 
  'lib/**/*.rb', 
  'test/**/*.rb',
  'doc/**/*',
  'build/rubyapp.rb',
  '*.blurb')

builder.rdoc_files << ['README', 'LICENSE', 'TODO', 'CHANGES']
builder.rdoc_files.glob('lib/**/*.rb', 'doc/**/*.rdoc', 'test/*.rb')

builder.clobber_files << %w(html pkg testdata)

builder.create_tasks

umlcoop_info = HostInfo.new(
  'umlcoop',
  'htdocs/software',
  'htdocs/packages')

local_info = HostInfo.new(
  'localhost',
  'working/projects/source2html/dummy/software',
  'working/projects/source2html/dummy/packages')

class RubyForgePublisher
  attr_reader :project, :proj_id, :user

  def initialize(projname, proj_id, user)
    @project = projname
    @proj_id = proj_id
    @user = user
  end

  def upload_web(app, localdir='html')
    Sys.run %{scp -rq html/* #{user}@rubyforge.org:/var/www/gforge-projects/#{project}}
  end

  def upload_package(app, *files)
    puts "Use the following link ..."
    puts "  http://rubyforge.org/project/showfiles.php?group_id=#{proj_id}"
    puts "to update the following release files."
    files.each { |f| puts "  #{f}" }
  end
end

#builder.publisher = SshPublisher.new(umlcoop_info)
builder.publisher = RubyForgePublisher.new('rake', 50, 'jimweirich')

# Additional dependencies beyond the standard

directory 'testdata'
task :test => ['testdata']

