# Rakefile for rake        -*- ruby -*-

require 'build/rubyapp'
require 'rake/testtask'
require 'rake/packagetask'
require 'rake/rdoctask'
require 'rake/contrib/sshpublisher'
require 'rake/contrib/rubyforgepublisher'

if `ruby -Ilib ./bin/rake --version` =~ /\S+$/
  PKG_VERSION = $&
else
  PKG_VERSION = "0.0.0"
end

desc "Default Task"
task :default => :test

builder = AppBuilder.new('rake')
builder.revision_command "ruby -Ilib ./bin/rake --version"

Rake::RDocTask.new { |rdoc|
  rdoc.rdoc_dir = 'html'
  rdoc.template = 'kilmer'
  rdoc.options << '--line-numbers'
  rdoc.rdoc_files.add('README', 'LICENSE', 'TODO', 'CHANGES')
  rdoc.rdoc_files.add('lib/**/*.rb', 'doc/**/*.rdoc', 'test/*.rb')
}.define

pkg = Rake::PackageTask.new("rake", PKG_VERSION)
pkg.package_files << 'install.rb'
pkg.package_files.add(
  '[A-Z]*',
  'bin/**/*', 
  'lib/**/*.rb', 
  'test/**/*.rb',
  'doc/**/*',
  'build/rubyapp.rb',
  '*.blurb')
pkg.package_files.reject! { |fn| fn =~ /\bCVS\b|~$/ }
pkg.define

Rake::TestTask.new { |t|
  t.libs << "test"
  t.verbose = true
}.define

load "publish.rf" if File.exist? "publish.rf"

directory 'testdata'
task :test => ['testdata']

Rake::TestTask.new(:contrib_test) { |ctest|
  ctest.pattern = 'test/contrib/test*.rb'
  ctest.verbose = true
}.define

desc "Install the application"
task :install do
  ruby "install.rb"
end

task :testall => [:test, :contrib_test]
