name: coverage

on: [push, pull_request]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
      with:
        ruby-version: '3.0'
    - name: Install dependencies
      run: gem install test-unit coveralls
    - name: Run test
      env:
        COVERALLS: "yes"
      run: ruby -Ilib exe/rake
