name: lint

on: [push, pull_request]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
      with:
        ruby-version: '3.0'
        bundler-cache: true
    - name: Run rubocop
      run: bundle exec rubocop
